In [2]:
# Numpy Basics/Fundamentals:-


In [ ]:
# Array Attributes:- Array attributes are properties of a NumPy array that describe its structure (shape, size, type, etc.).-> Like metadata of the array
# 1.ndim:- gives number of dimension from an given array
# 2.shape:- gives rows and columns in each dimension
# 3.size:- gives number of items in the given array
# 4.itemsize:- gives size of the memory used by each item -> In Bytes
# 5.dtype:- gives the datatype of the array with size(i.e 32,64 bytes)
# 6.nbytes:- gives total memory used
# 7.reshape:- helps to change the shape of the array(DIMENSION)
# 8.T:- helps to transpose of the array

In [4]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [9]:
# Changing the datatype of the exisiting array:-
# astype:-
a3.dtype # by default = 64
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [18]:
# Topic:- Array operations:-
# 1. Scaler operations
a1 ** 2 # each item of the array will be multiplied by the scaler(2)


# 2. relational:- all kinds of operators can be used FOR THE ARRAY
a2 > 5
a2 == 10


# Vector Operations:-
# 1. Arithmetic Operators:- shape of the arrays should be same, where the opertions is being performed
a3 * a3


array([[[ 0,  1],
        [ 4,  9]],

       [[16, 25],
        [36, 49]]])

In [27]:
# Array Functions:-

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

# 1. max/min/sum/product(prod)
np.max(a1)
np.sum(a1)
np.max(a1,axis=1) # 1=rows, 0=columns -> can be used to find min/max from the any particular rows and columns


# stastical function:-mean/median/std/var:-
np.mean(a1,axis=1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis=1)


# Trignometric Functions:-
np.sin(a1)
np.cos(a2)
np.tan(a3)


# Dot product:- b/w the two matrices
np.dot(a2,a3)


# Log and exponents:-
np.log(a1)
np.exp(a1)


# functions:- round/floor/cell
# floor() -> returns the largest integer less than or equal to the given number.
# ceil() -> returns the smallest integer greater than or equal to the given number.
# round() -> returns the nearest integer value (or specified decimal precision).
np.floor(np.random.random((2,3))*100)

array([[54., 51., 48.],
       [99., 35., 56.]])

In [ ]:
# Concept in NUMPY:- Indexing and slicing:-
# 1.