In [8]:
# Numpy Basics/Fundamentals:-


In [9]:
# Array Attributes:- Array attributes are properties of a NumPy array that describe its structure (shape, size, type, etc.).-> Like metadata of the array
# 1.ndim:- gives number of dimension from an given array
# 2.shape:- gives rows and columns in each dimension
# 3.size:- gives number of items in the given array
# 4.itemsize:- gives size of the memory used by each item -> In Bytes
# 5.dtype:- gives the datatype of the array with size(i.e 32,64 bytes)
# 6.nbytes:- gives total memory used
# 7.reshape:- helps to change the shape of the array(DIMENSION)
# 8.T:- helps to transpose of the array

In [10]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [11]:
# Changing the datatype of the exisiting array:-
# astype:-
a3.dtype # by default = 64
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [12]:
# Topic:- Array operations:-
# 1. Scaler operations
a1 ** 2 # each item of the array will be multiplied by the scaler(2)


# 2. relational:- all kinds of operators can be used FOR THE ARRAY
a2 > 5
a2 == 10


# Vector Operations:-
# 1. Arithmetic Operators:- shape of the arrays should be same, where the opertions is being performed
a3 * a3


array([[[ 0,  1],
        [ 4,  9]],

       [[16, 25],
        [36, 49]]])

In [13]:
# Array Functions:-

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

# 1. max/min/sum/product(prod)
np.max(a1)
np.sum(a1)
np.max(a1,axis=1) # 1=rows, 0=columns -> can be used to find min/max from the any particular rows and columns


# stastical function:-mean/median/std/var:-
np.mean(a1,axis=1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis=1)


# Trignometric Functions:-
np.sin(a1)
np.cos(a2)
np.tan(a3)


# Dot product:- b/w the two matrices
#np.dot(a2,a3)


# Log and exponents:-
np.log(a1)
np.exp(a1)


# functions:- round/floor/cell
# floor() -> returns the largest integer less than or equal to the given number.
# ceil() -> returns the smallest integer greater than or equal to the given number.
# round() -> returns the nearest integer value (or specified decimal precision).
np.floor(np.random.random((2,3))*100)

array([[31., 71., 21.],
       [78.,  1.,  2.]])

In [73]:
# Concept in NUMPY:- Indexing and slicing:-
# 1. Indexing similar to python starts from 0 = when positive and -1 = when negative
# Indexing for 2D Arrays:-
a2 # if we want to find a particular we use (rows,followed by columns)
a2[2,3]


# Indexing For 3d arrays:-
a3
# a3(inwhich 2d array the element exists,rows,columns) bcz 3d array coes from 2d arrays
a3[1,0,1]



## SLICING:-
# fetch 2,3,4 elements from a1
a1 = np.arange(10)
a1
a1[2:5]

# InCase for 2D arrays:-
a2
a2[0,:] # Gives 0th rows and each columns
a2[:,2]
a2[::2,::3] #IMP = For all corners numbers
a2[::2,1::2] # Gives 1,3,9,11 -> works = gives all rows except 2nd, gives columns from 1 to last except 2
a2[1::2,0::3] # Gives 4,7 In the O/P can be a2[1,::3]
a2[0:2,1:]




# In case of 3d ARRAY:-
a3 = np.arange(27).reshape(3,3,3)
a3
a3[1] # Gives middle array
a3[::2] # Gives 0th and 2nd array
#a3[0,1,:]
a3[1,:,1]
a3[2,1::1,1::1] # gives 22,23,25,26 can be also a3[2,1:,1:]
a3[::2,0,::2] # gives 0,2,18,20

array([[ 0,  2],
       [18, 20]])

In [ ]:
# Topic:- Iterating!!
# Loops canbe run on the numpy(array)
# for i in a1:
 #print(i)

# for i in a2:
 # print(i)

# for i in a3:
 # print(i)

  # code for traversing indivual elements of the array:-
for i in np.nditer(a3):
    print(i)

In [ ]:
# Concept Of Reshaping and its functions:-
# 1. reshape():- helps to change the sie of dimension as per needed
# 2. Transpose():- changes r-c and c-r
# 3. Ravel():- can convert any dimension of array into 1D array!!! ->
a3.ravel()



In [86]:
# Concept of Stacking:- (Adds Up) Two Numpy Arrays -> shape should be same for the numpy arrays -> canbe of of two types
# 1. Horizontal Stacking ->
# 2. Vertical Stacking ->
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))
np.vstack((a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [92]:
# Concept of Splitting:- opposite of stacking:-
# 1. horizontal split -> same as vertical stacking
# 2. vertical split -> same as horizonatal stacking

np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

Advanced Indexing

In [37]:
# Concept of Advanced Indexing:-
# 1. Fancy Indexing:-
import numpy as np
a = np.arange(24).reshape(6,4)
a
# a[[0,2,3]] # Gives only 2nd and 3rd rows of the array
a[:,[0,2,3]]


# 2. Boolean Indexing:- indexing with some conditions!!
a = np.random.randint(1,100,24).reshape(6,4)
a
a[a%2==0] # canbe used as boolean mask -> where the items is true only that are left , false elements are gone


array([ 2, 26, 56, 96, 28, 58, 72, 48, 90, 14, 78, 40, 82, 66, 86])

Broadcasting